addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.8.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-scalafix" % "0.8.4")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.20.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.8.2")
