addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.7.6")
addSbtPlugin("org.typelevel" % "sbt-typelevel-scalafix" % "0.7.6")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.18.1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.6.2")
