addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.7.4")
addSbtPlugin("org.typelevel" % "sbt-typelevel-scalafix" % "0.7.4")
addSbtPlugin("org.foundweekends.giter8" %% "sbt-giter8" % "0.16.2")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.17.0")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.6.2")
